In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.8.2


In [5]:
#creating tensor with tf.constant
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#checking dimension of tesnor usimg ndim
scalar.ndim

0

In [7]:
#creating vector
vector=tf.constant((10,10))
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [9]:
#checking of dimension of vectror
vector.ndim

1

In [10]:
#creating matrix with tf.constant
matrix=tf.constant([[10,7],[7,10]])
print(matrix)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [11]:
matrix.ndim

2

In [12]:
#creating another matrix for using dtype feature
another_matrix=tf.constant([[7.,10.],
                            [5.0,25.5],
                            [8.5,9.5]])

In [13]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 7. , 10. ],
       [ 5. , 25.5],
       [ 8.5,  9.5]], dtype=float32)>

In [14]:
another_matrix=tf.constant([[7.,10.],
                            [5.0,25.5],
                            [8.5,9.5]],dtype=tf.float16)

In [15]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7. , 10. ],
       [ 5. , 25.5],
       [ 8.5,  9.5]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [17]:
#creating same tensor with tf.Variable
changeble_tensor=tf.Variable([10.5,7.5])

In [18]:
print(changeble_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.5,  7.5], dtype=float32)>


In [20]:
#lets try to chnage of a elements in changle tesnor
changeble_tensor[0]=7.7 #not posiible with direct idea


TypeError: ignored

In [21]:
changeble_tensor[0].assign(7.7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([7.7, 7.5], dtype=float32)>

In [22]:
unchangeble_tesnor=tf.constant([10,7])
print(unchangeble_tesnor)

tf.Tensor([10  7], shape=(2,), dtype=int32)


In [23]:
unchangeble_tesnor[0].assign(7.7)  #not changing bcz it is constant

AttributeError: ignored

In [ ]:
#creating random vector
random_1=tf.random.Generator.from_seed(55)
random_1=random_1.normal(shape=(3,2))

In [ ]:
print(random_1)

In [24]:
random_2=tf.random.Generator.from_seed(55)
random_2=random_2.uniform(shape=(3,2))
print(random_2)
random_1,random_2, random_1==random_2

tf.Tensor(
[[0.02760839 0.99757504]
 [0.52172756 0.20307171]
 [0.7182547  0.84263575]], shape=(3, 2), dtype=float32)


NameError: ignored

In [ ]:
#suffling order of tesnor
not_shuffled=tf.constant([[10,7],
                          [7,10],
                          [2,5]])

In [25]:
not_shuffled.ndim
#lets shiffled our non shuffled tesnor
tf.random.shuffle(not_shuffled)   #here shuffled only in shape(3,2) in 3 row side only

NameError: ignored

In [ ]:
#again shuffled 
tf.random.shuffle(not_shuffled)

In [26]:
tf.random.shuffle(not_shuffled,seed=55)

NameError: ignored

In [ ]:
tf.ones((10,7))

In [27]:
tf.zeros((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [28]:
#you can turn numpy array in to tesnor
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

# X=tf.constant(some_matrix) #capital is used for matrix or tensor
# y=tf.vector(constant)  #non-capital for vectors  

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A=tf.constant(numpy_A)
print(A)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [30]:
A=tf.constant(numpy_A,shape=(2,3,4))
print(A)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [31]:
#indexing tensor
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [32]:
#get the first 2 elements of each dimension
#rank_4_tensor[:2,:2,:2,:2]
rank_4_tensor=tf.zeros((2,3,4,5),dtype=tf.float16)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float16, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float16)>

In [33]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float16, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float16)>

In [34]:
rank_4_tensor[:1,:1,:1].shape
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float16, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float16)>

In [35]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [36]:
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])

In [37]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [38]:
#adding extra dimension to rank 2 tesnsor
rank_3_tesnor=rank_2_tensor[...,tf.newaxis]
rank_3_tesnor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [39]:
#alternative to tf.axies
tf.expand_dims(rank_2_tensor,axis=-1)  #'-1' means expand the final axies

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
tf.expand_dims(rank_2_tensor,axis=0)  #'0' means expand the first axies number show position of extra dimension which added 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [41]:
tf.expand_dims(rank_2_tensor,axis=1)  #'1' means expand the first axies number show position of extra dimension which added 

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

#maniuplating tensor

In [42]:
#add value in tesnor
tensor=tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:

#orignal tensor remains will be unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
#multiplicatio
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [46]:
#we can used tensorflow built in library for use
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix multiplication

In [47]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [49]:
#matrix multiplication in tensor is also using '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [50]:
X=tf.constant([[1,2],
               [2,3],
               [3,4]])
Y=tf.constant([[5,6],
               [6,7],
               [7,8]])

In [51]:
X@Y

InvalidArgumentError: ignored

In [ ]:
Y=tf.reshape(Y,shape=(2,3))

In [52]:
X@Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X,Y).shape

In [ ]:
# transpose and reshape clear idea 
X, tf.transpose(X), tf.reshape(X,shape=(2,3))

Dot product of matrix

In [53]:
# can be done by using
# tf.matmul
# tf.tensordot

In [54]:
#perform dot product of x and y
Y=tf.constant([[5,6],
               [6,7],
               [7,8]])
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[38, 44],
       [56, 65]], dtype=int32)>

chnging datatype of tensor

In [55]:
B=tf.constant([10.5,7.5])
B.dtype

tf.float32

In [56]:
c=tf.constant([3,4])
c.dtype

tf.int32

In [57]:
#chnage float32 to float16 (reduce precision)
D=tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.5,  7.5], dtype=float16)>,
 tf.float16)

In [58]:
E=tf.cast(B,dtype=tf.float32)
E ,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.5,  7.5], dtype=float32)>,
 tf.float32)

Agrrigation in tensor max, min

In [59]:
#get absolute value
D=tf.constant([-7.5,-5.5])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7.5, 5.5], dtype=float32)>

In [60]:
#creating large random tesnor values between 0  to 100 of size 50
e=tf.constant(np.random.randint(0,100,50))
e 

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 82, 67, 27, 32, 50, 69, 56, 47, 25, 54, 92, 10, 25, 81,  7,  7,
       84, 94, 22, 80, 13, 12, 60, 50, 90, 48, 53, 31, 29, 40, 76, 58, 88,
       45, 42,  2, 94, 41, 90, 60, 48, 81, 44,  3, 80,  3, 10, 52, 51])>

In [61]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [62]:
np.min(e)

2

In [63]:
print(tf.reduce_max(e))
print(np.max(e))

tf.Tensor(94, shape=(), dtype=int64)
94


In [64]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [65]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2475>

In [66]:
# for std deviation in tesnor flow
#tfp.stats.variance(e)     didn't work it out so

importing tensor flow probability

In [67]:
import tensorflow_probability as tfp

In [68]:
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=773>

##std deviation

In [69]:
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.81025>

##Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [70]:
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=773.41>

In [71]:
tf.random.set_seed(55)

In [72]:
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.11019313, 0.77135265, 0.00816071, 0.6490395 , 0.6785451 ,
       0.06639993, 0.4311856 , 0.57631946, 0.2077086 , 0.6224432 ,
       0.9599656 , 0.91845477, 0.91761684, 0.53194296, 0.7459427 ,
       0.15139258, 0.73857045, 0.34166527, 0.95904124, 0.39281034,
       0.44954646, 0.67659163, 0.94830847, 0.60771453, 0.66323924,
       0.1294272 , 0.45881665, 0.8812107 , 0.28770614, 0.80997705,
       0.26492465, 0.20084298, 0.60809696, 0.38200402, 0.14240897,
       0.12760866, 0.473148  , 0.858179  , 0.42604935, 0.918911  ,
       0.24817514, 0.20454597, 0.23529124, 0.6164473 , 0.3019017 ,
       0.83857715, 0.8233564 , 0.76089835, 0.8097205 , 0.73268366],
      dtype=float32)>

In [73]:
#find arguemnt maximun positional value
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [74]:
#index on your largest number position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9599656>

In [75]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9599656>

In [76]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [77]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.00816071>

In [78]:
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.00816071>

Squezzing tensor removing all single dimensions

In [79]:
g=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])

In [80]:
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6031927 , 0.17381382, 0.65605724, 0.8868109 , 0.69147205,
           0.22699702, 0.6421751 , 0.46517444, 0.9425099 , 0.74188757,
           0.19287968, 0.82944286, 0.17296338, 0.19507647, 0.15316498,
           0.46172583, 0.35352826, 0.99657905, 0.54987454, 0.45215797,
           0.7978827 , 0.8867403 , 0.68997574, 0.2801628 , 0.728467  ,
           0.80284965, 0.8721098 , 0.2049017 , 0.65276647, 0.51969194,
           0.88131046, 0.01533806, 0.8572235 , 0.40104103, 0.9436432 ,
           0.41093826, 0.8944974 , 0.96792364, 0.36756432, 0.24098456,
           0.5751929 , 0.6613612 , 0.89248013, 0.05685484, 0.13465369,
           0.9024986 , 0.67394626, 0.05293524, 0.16245484, 0.9196354 ]]]]],
      dtype=float32)>

In [81]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [82]:
g_squeez=tf.squeeze(g)
g_squeez, g_squeez.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6031927 , 0.17381382, 0.65605724, 0.8868109 , 0.69147205,
        0.22699702, 0.6421751 , 0.46517444, 0.9425099 , 0.74188757,
        0.19287968, 0.82944286, 0.17296338, 0.19507647, 0.15316498,
        0.46172583, 0.35352826, 0.99657905, 0.54987454, 0.45215797,
        0.7978827 , 0.8867403 , 0.68997574, 0.2801628 , 0.728467  ,
        0.80284965, 0.8721098 , 0.2049017 , 0.65276647, 0.51969194,
        0.88131046, 0.01533806, 0.8572235 , 0.40104103, 0.9436432 ,
        0.41093826, 0.8944974 , 0.96792364, 0.36756432, 0.24098456,
        0.5751929 , 0.6613612 , 0.89248013, 0.05685484, 0.13465369,
        0.9024986 , 0.67394626, 0.05293524, 0.16245484, 0.9196354 ],
       dtype=float32)>, TensorShape([50]))

##one hot-encoding tensor

In [83]:
# create a list of indices
some_list=[0,1,2,3,4]  #could be red,green,blue,purple

In [84]:
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [85]:
tf.one_hot(some_list,depth=4,on_value='dev',off_value='ishu')

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'dev', b'ishu', b'ishu', b'ishu'],
       [b'ishu', b'dev', b'ishu', b'ishu'],
       [b'ishu', b'ishu', b'dev', b'ishu'],
       [b'ishu', b'ishu', b'ishu', b'dev'],
       [b'ishu', b'ishu', b'ishu', b'ishu']], dtype=object)>

squaring,log,squre_root

In [86]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [89]:
tf.math.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

##tensorflow and nupmy 

In [90]:
#create tensor directly from numpy array

In [92]:
o=tf.constant(np.array([1.5,2,3]))
o

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.5, 2. , 3. ])>

In [93]:
#covert tensor to numpy array
np.array(o)

array([1.5, 2. , 3. ])

In [95]:
o.numpy,type(o.numpy())

(<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.5, 2. , 3. ])>>,
 numpy.ndarray)

In [2]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Sun Jul 31 14:15:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------